services:
  - type: web
    name: sushashank-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
