# Render configuration for the portfolio server
# Reference: https://render.com/docs/deploy-node-express-app

services:
  - type: web
    name: portfolio-server
    env: node
    # Build command to install dependencies
    buildCommand: npm install
    # Start command for the application
    startCommand: npm start
    # Environment variables
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      # Add your MongoDB connection string from Render's dashboard or environment variables
      - key: MONGODB_URI
        fromDatabase:
          name: portfolio-db
          property: connectionString
      # CORS configuration - update with your frontend URL
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,http://localhost:3000

    # Auto-deploy from Git (optional)
    autoDeploy: true
    
    # Health check path (optional)
    healthCheckPath: /api
    
    # Plan settings (free tier)
    plan: free
    
    # Region (optional)
    region: oregon  # or choose a region closer to your users

# Add database configuration if needed
databases:
  - name: portfolio-db
    databaseName: portfolio
    user: shashankreddy
    plan: free  # or 'starter' for production use
