services:
  - type: web
    name: sushashank-portfolio-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will prompt Render to ask for this value during deployment
